### ISSUE TITLE
Startup client error

### ISSUE THREAD

**Issue by Vealor** [OCB7D2D/ClaimAutoRepair#1]
I'm hosting a dedicated server on ubuntu 20.04 using steamcmd and put the mod in the `Mods` folder.

I put the mod locally on client side on Windows 10 in the `Mods` folder.

On connection to the server, this is the error recieved (note: this is recent version of A20)
![image](https://user-images.githubusercontent.com/6099022/146453414-e43396b0-9974-4872-8c88-2bec853d7beb.png)

Couldn't find any information to fix this, please help 😄

**Comment by mgreter** [comment]
Did you disable EAC? Make double sure you did!

**Comment by Vealor** [comment]
it's disabled server side
` <property name="EACEnabled"                             value="false"/>                         <!-- Enables/Disables EasyAntiCheat -->`

**Comment by mgreter** [comment]
And did you also disable it client side? Please check your whole log.
You've not provided enough info for me to investigate anything further.
So closing this out until you can provide more info (logs etc). Thx!

**Comment by AMXBus** [comment]
@Vealor Solved it on a Windows Server Client with the mod being copied over to the client mod folder. Either the mod can't be run standalone on server and the dev did not mention that in the git or never tested it himself on a server. Either way no reason for @mgreter to be condescending.

**Comment by Vealor** [comment]
I've checked logs and provided what's available unless I'm missing something.  If there's another area, it would be helpful for you to let me know.  I'm likely not the only person having this issue.

If you developed the mod for yourself that's fine, but until I can get assistance or it's updated I won't be able to use the mod.

**Comment by mgreter** [comment]
I would need at least a log as a text file (the full log). Not just a tiny screenshot.
Only thing I can say is that you will get exactly that error if you don't disable EAC.
